# Generated by Django 4.2.16 on 2024-12-13 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpetaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carpeta', models.CharField(max_length=45)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('numero_expediente', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(default='Preliminar', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=45, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=45, null=True)),
                ('dni', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=45, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Imputado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('dni', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=45)),
                ('correo_electronico', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
                ('carpeta_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputados', to='api.carpetafiscal')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoInvestigado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('archivo', models.FileField(upload_to='archivos_investigados/')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=45)),
                ('imputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_investigado', to='api.imputado')),
                ('subido_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_investigado_subidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoDisposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=45)),
                ('archivo', models.FileField(upload_to='archivos_disposicion/')),
                ('carpeta_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_disposicion', to='api.carpetafiscal')),
                ('subido_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_disposicion_subidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
