# Generated by Django 4.2.16 on 2024-12-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_carpetafiscal_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpetafiscal',
            name='estado',
            field=models.CharField(max_length=45),
        ),
    ]
