# Generated by Django 4.2.16 on 2024-12-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_carpetafiscal_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpetafiscal',
            name='estado',
            field=models.CharField(default='Investigación', max_length=45),
        ),
    ]
